python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_max_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_double_mean_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_gaussian_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_percentile_initperc999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_percentile_initperc9999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_percentile_initperc99999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_max_init_a_init_percentile_initperc999999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_max_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_double_mean_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_gaussian_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_percentile_initperc999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_percentile_initperc9999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_percentile_initperc99999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_double_mean_init_a_init_percentile_initperc999999.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_gaussian_init_a_init_max_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_gaussian_init_a_init_double_mean_init.py
python3 train.py --workdir=/home/clemens/init_ablation_w --config=efficientnet/configs/init_ablation_w2a2//efficientnet-lite0_w2a2_w_init_gaussian_init_a_init_gaussian_init.py
