#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N pc_snn_alpha_0.5_2
#$ -o ./logs/runs/output_pc_snn_pc_snn_alpha_0.5_2.txt
#$ -e ./logs/runs/error_pc_snn_pc_snn_alpha_0.5_2.txt
module load python cuda/10.2
setenv XLA_FLAGS --xla_gpu_cuda_data_dir=/afs/crc.nd.edu/x86_64_linux/c/cuda/10.2
setenv OMP_NUM_THREADS $NSLOTS
python pc_snn.py  --alpha 0.5 --seed 8627169 --log-file logs/pc_snn_alpha.csv
