#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q gpu@@joshi
#$ -l gpu_card=1
#$ -N snn_sweeps_l_rate_0.0001_2
#$ -o ./logs/runs/output_snn_sweeps_snn_sweeps_l_rate_0.0001_2.txt
#$ -e ./logs/runs/error_snn_sweeps_snn_sweeps_l_rate_0.0001_2.txt
module load python cuda/10.2
setenv XLA_FLAGS --xla_gpu_cuda_data_dir=/afs/crc.nd.edu/x86_64_linux/c/cuda/10.2
setenv OMP_NUM_THREADS $NSLOTS
python bptt_snn.py --l_rate 0.0001 --seed 8627169 --log-file logs/snn_sweeps_l_rate.csv
