#!/bin/csh 
#$ -M cschaef6@nd.edu 
#$ -m abe
#$ -q 
#$ -l gpu_card=1
#$ -N gpu@@joshisnn_pattern_a1_700-400-250_lr_1e-09_a2_0.1_a3_0.1_thr_0.01_0
#$ -o ./logs/output_snn_pattern_snn_pattern_a1_700-400-250_lr_1e-09_a2_0.1_a3_0.1_thr_0.01_0.txt
#$ -e ./logs/error_snn_pattern_snn_pattern_a1_700-400-250_lr_1e-09_a2_0.1_a3_0.1_thr_0.01_0.txt
module load python
setenv OMP_NUM_THREADS $NSLOTS
python bptt_snn.py --architecture "700-400-250" --l_rate 1e-09 --alpha 700-400-250 --alpha_vr 0.1 --thr 0.01 --seed 193012823 --log-file snn_pattern.csv