# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on: [push, pull_request]
  # Triggers the workflow on push or pull request events but only for the master branch
  #push:
  #  branches: [ master ]
  #pull_request:
  #  branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  #workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install flake8
      - name: Lint with flake8 
        run: |
          flake8 --ignore=W503,E111,E114 *.py
          flake8 --ignore=W503,E111,E114 examples/efficientnet/*.py
          flake8 --ignore=W503,E111,E114 examples/resnet/*.py
          flake8 --ignore=W503,E111,E114 examples/small_cnn/*.py
  typecheck_pytype:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install pytype jax jaxlib scipy numpy flax ml_collections clu tensorflow
      - name: Type check with pytype
        run: |
          pytype *.py
  unittest:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          pip install jax==0.2.24 jaxlib==0.1.73 numpy==1.21.3 flax==0.3.5 tensorflow-datasets==4.4.0 ml_collections==0.1.0 clu==0.0.6
      - name: Run unit tests
        run: |
          ./aux_data_download.sh
          python pc_modular_test.py
          python flax_qconv_test.py
          python flax_qdense.py
          python quant_test.py
          python batchnorm_test.py
          cd examples/efficientnet/
          python models_test.py
          python train_test.py
          cd ../resnet/
          python models_test.py
          python train_test.py
